// Generated by `CALIBRATE=1 npx vitest run packages/bench/src/calibrate.test.ts`
// — do not edit by hand.
//
// Each row: positions the evaluator scored up to `score` won `points` on
// average when rolled out to the end, and were won outright `winRate` of
// the time.
import type { CalibrationPoint } from './calibration.js';

export const CALIBRATION: readonly CalibrationPoint[] = [
  { score: 0.0566, points: 0.0940, winRate: 0.5163, samples: 60 },
  { score: 0.1586, points: 0.1156, winRate: 0.5489, samples: 60 },
  { score: 0.2428, points: 0.1611, winRate: 0.5489, samples: 60 },
  { score: 0.3374, points: 0.3453, winRate: 0.5925, samples: 60 },
  { score: 0.4265, points: 0.3453, winRate: 0.5925, samples: 60 },
  { score: 0.5117, points: 0.3685, winRate: 0.5925, samples: 60 },
  { score: 0.5933, points: 0.4585, winRate: 0.6342, samples: 60 },
  { score: 0.6600, points: 0.5261, winRate: 0.6374, samples: 60 },
  { score: 0.7345, points: 0.7681, winRate: 0.7157, samples: 60 },
  { score: 0.7837, points: 0.7681, winRate: 0.7157, samples: 60 },
  { score: 0.8455, points: 0.8553, winRate: 0.7157, samples: 60 },
  { score: 0.8910, points: 0.9929, winRate: 0.7567, samples: 60 },
  { score: 0.9184, points: 1.1546, winRate: 0.7675, samples: 60 },
  { score: 0.9536, points: 1.1546, winRate: 0.7675, samples: 60 },
  { score: 0.9783, points: 1.4778, winRate: 0.8042, samples: 60 },
  { score: 0.9887, points: 1.5697, winRate: 0.8544, samples: 60 },
  { score: 0.9956, points: 1.6442, winRate: 0.8556, samples: 60 },
  { score: 0.9986, points: 1.9628, winRate: 0.9292, samples: 60 },
  { score: 0.9998, points: 2.0021, winRate: 0.9365, samples: 60 },
  { score: 1.0000, points: 2.5140, winRate: 0.9899, samples: 60 },
];
