import { type LoadedProblem, type Problem, load } from './problem.js';
import { GENERATED_PROBLEMS } from './problems.generated.js';

/**
 * The problem set. Static data compiled into the Worker rather than rows in
 * D1: it is the same for every player, it is regenerated by rebuilding rather
 * than by writing, and keeping it out of the database means the answers cannot
 * be read by anything that only has a database connection.
 */
export const PROBLEMS: readonly Problem[] = GENERATED_PROBLEMS;

const BY_ID = new Map(PROBLEMS.map((problem) => [problem.id, problem]));

export function problemById(id: string): Problem | undefined {
  return BY_ID.get(id);
}

export function loadById(id: string): LoadedProblem | null {
  const problem = BY_ID.get(id);
  return problem ? load(problem) : null;
}
